spring.application.name=vkr

spring.datasource.url=jdbc:postgresql://localhost:5432/electronika

# Имя пользователя БД
spring.datasource.username=postgres

# Пароль пользователя БД
spring.datasource.password=admin1234

# Драйвер базы данных
spring.datasource.driver-class-name=org.postgresql.Driver